# Generated by Django 6.1 on 2026-08-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ক্যাটাগরির নাম')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='কাস্টমারের নাম')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='মোবাইল নম্বর')),
                ('service_details', models.TextField(verbose_name='কাজের বিবরণ (যেমন: মগ প্রিন্ট)')),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মোট বিল')),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='অগ্রিম পরিশোধ')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='ডেলিভারি হয়েছে কি?')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('Sale', 'পণ্য বিক্রি'), ('Service', 'সার্ভিস আয়'), ('Expense', 'দোকানের খরচ'), ('MFS', 'বিকাশ/নগদ লেনদেন')], max_length=20, verbose_name='লেনদেনের ধরণ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='টাকার পরিমাণ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='বিবরণ বা নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='সময়')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ক্রয় মূল্য')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='বিক্রয় মূল্য')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='স্টক পরিমাণ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='ক্যাটাগরি')),
            ],
        ),
    ]
