# Generated by Django 6.1 on 2026-08-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ক্রয় মূল্য (মোট)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='পণ্য'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='লাভ/ক্ষতি'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_details',
            field=models.TextField(verbose_name='কাজের বিবরণ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='বিক্রয় মূল্য (মোট)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='নোট'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Sale', 'পণ্য বিক্রি'), ('Service', 'সার্ভিস আয়'), ('Expense', 'দোকানের খরচ')], max_length=20, verbose_name='লেনদেনের ধরণ'),
        ),
    ]
