# Generated by Django 6.1 on 2026-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_transaction_buy_price_transaction_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='খরচের খাত')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='টাকার পরিমাণ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='তারিখ')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='সার্ভিসের নাম (যেমন: মগ প্রিন্ট)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ক্রয় মূল্য'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='বিক্রয় মূল্য'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='ডেলিভারি হয়েছে কি?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='বিক্রয়/আয় মূল্য (মোট)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ক্রয় মূল্য (মোট)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Sale', 'পণ্য বিক্রি'), ('Service', 'কম্পিউটার/মগ প্রিন্ট ও সার্ভিস'), ('MFS', 'মোবাইল ব্যাংকিং (বিকাশ/নগদ) আয়')], max_length=20, verbose_name='লেনদেনের ধরণ'),
        ),
    ]
