# Generated by Django 6.1 on 2026-08-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_expense_transaction_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='কাস্টমারের নাম')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='মোবাইল নম্বর')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ঠিকানা')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='যোগের তারিখ')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='টাকার পরিমাণ')),
                ('trans_type', models.CharField(choices=[('due_given', 'বাকি দেওয়া (Due Given)'), ('due_paid', 'টাকা পরিশোধ (Paid)')], max_length=20, verbose_name='লেনদেনের ধরণ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='বিবরণ / নোট')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='তারিখ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='কাস্টমার')),
            ],
        ),
    ]
