# Generated by Django 6.1 on 2026-08-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_customertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='পণ্য বা সার্ভিসের বিবরণ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='মোবাইল নম্বর (ঐচ্ছিক)'),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='অতিরিক্ত নোট'),
        ),
    ]
