# Generated by Django 6.1 on 2026-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customertransaction_item_name_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customertransaction',
            name='item_name',
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='category',
            field=models.CharField(choices=[('Product', 'পণ্য ক্রয় (Product)'), ('Printing', 'প্রিন্টিং সার্ভিস (Printing)'), ('MFS', 'মোবাইল ব্যাংকিং (MFS)'), ('Other', 'অন্যান্য (Other)')], default='Product', max_length=20, verbose_name='খাত/বিভাগ'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='item_details',
            field=models.CharField(default='-', max_length=250, verbose_name='পণ্য/সার্ভিসের নাম ও বিবরণ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='নোট (ঐচ্ছিক)'),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='trans_type',
            field=models.CharField(choices=[('due_given', 'বাকি দেওয়া (Due Given)'), ('due_paid', 'টাকা পরিশোধ (Paid)')], default='due_given', max_length=20, verbose_name='লেনদেনের ধরণ'),
        ),
    ]
